import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Reservoir from '../components/another/Reservoir'
import AntLoading from '../components/loading/antLoading'
import FullCircle from '../components/loading/fullCircle'
import ToBeContinued from '../components/loading/toBeContinued'
import TypeWriter from '../components/loading/typeWriter'
import LoadingSize from '../components/loading/loadingSize'
import ToBeContinuedVTwo from '../components/loading/toBeContinuedVTwo'
import LinearLoading from '../components/loading/linearLoading'
import AloneMan from '../components/loading/aloneMan'
import NimeShaban from '../components/loading/nimeShaban'
import TransparentLoading from '../components/loading/transparentLoading'
import LoadingImage from '../components/loading/imageLoading'
import CirclesFollowEachOthe from '../components/loading/circlesFollowEachOther'
import SemiCircles from '../components/loading/semiCircles'
import StoryLoading from '../components/loading/storyLoading'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.border}>
          <Reservoir data={<AloneMan />} />
          <Reservoir data={<StoryLoading />} />
          <Reservoir data={<LoadingImage />} />
          <Reservoir data={<CirclesFollowEachOthe />} />
          <Reservoir data={<AntLoading.LodingTowLine />} />
          <Reservoir data={<AntLoading.loadingOnLine />}/>
          <Reservoir data={<AntLoading.loadingUnderLine />}/>
          <Reservoir data={<AntLoading.LoadingAboveLine />} />
          <Reservoir data={<LinearLoading />} />
          <Reservoir data={<NimeShaban />} />
          <Reservoir data={<TransparentLoading />} />
          <Reservoir data={<ToBeContinued />} />
          <Reservoir data={<ToBeContinuedVTwo />} />
          <Reservoir data={<TypeWriter />} />
          <Reservoir data={<LoadingSize />} />
          <Reservoir data={<FullCircle />} />
          <Reservoir data={<SemiCircles/>}/>
          <Reservoir />
          <Reservoir />
          <Reservoir />
          <Reservoir />
          <Reservoir />
          <Reservoir />
        </div>
      </main>
    </div>
  )
}
